apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ramann123/product-service:latest  # Replace with your Docker Hub image path
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/productdb
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort  # Exposes the service externally
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: product-service
