apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.productService.replicas }}  # Use value from values.yaml
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: {{ .Values.productService.image }}  # Use image from values.yaml
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/productdb
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort  # Exposes the service externally
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: {{ .Values.productService.nodePort }}  # Use nodePort from values.yaml
  selector:
    app: product-service

